
package vistas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import datos.*;

/**
 *
 * @author oscar
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        lblUsuario.setText("Usuario: " + Sesion.getUsuario().getNombre() + " " + Sesion.getUsuario().getApellido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        lblUsuario = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        subMenuUsuario = new javax.swing.JMenu();
        subMenuCliente = new javax.swing.JCheckBoxMenuItem();
        subMenuCuenta = new javax.swing.JCheckBoxMenuItem();
        subMenuDepartamento = new javax.swing.JCheckBoxMenuItem();
        subMenuEstado = new javax.swing.JCheckBoxMenuItem();
        subMenuTipoCuenta = new javax.swing.JCheckBoxMenuItem();
        menuMovimientos = new javax.swing.JMenu();
        subMenuMovimiento = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        subMenuClientes = new javax.swing.JMenuItem();
        subMenuDepartamentos = new javax.swing.JMenuItem();
        subMenuEstados = new javax.swing.JMenuItem();
        subMenuTipoCuentas = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        subMenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        escritorio.setLayer(lblUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(510, Short.MAX_VALUE)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        subMenuUsuario.setText("Catalogos");

        subMenuCliente.setSelected(true);
        subMenuCliente.setText("Cliente");
        subMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuClienteActionPerformed(evt);
            }
        });
        subMenuUsuario.add(subMenuCliente);

        subMenuCuenta.setSelected(true);
        subMenuCuenta.setText("Cuenta");
        subMenuCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCuentaActionPerformed(evt);
            }
        });
        subMenuUsuario.add(subMenuCuenta);

        subMenuDepartamento.setSelected(true);
        subMenuDepartamento.setText("Departamento");
        subMenuDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuDepartamentoActionPerformed(evt);
            }
        });
        subMenuUsuario.add(subMenuDepartamento);

        subMenuEstado.setSelected(true);
        subMenuEstado.setText("Estado");
        subMenuEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuEstadoActionPerformed(evt);
            }
        });
        subMenuUsuario.add(subMenuEstado);

        subMenuTipoCuenta.setSelected(true);
        subMenuTipoCuenta.setText("Tipo Cuenta");
        subMenuTipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuTipoCuentaActionPerformed(evt);
            }
        });
        subMenuUsuario.add(subMenuTipoCuenta);

        barraMenu.add(subMenuUsuario);

        menuMovimientos.setText("Movimientos");

        subMenuMovimiento.setText("Movimiento");
        menuMovimientos.add(subMenuMovimiento);

        barraMenu.add(menuMovimientos);

        menuReportes.setText("Reportes");

        subMenuClientes.setText("Listado clientes");
        subMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuClientesActionPerformed(evt);
            }
        });
        menuReportes.add(subMenuClientes);

        subMenuDepartamentos.setText("Listado departamentos");
        subMenuDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuDepartamentosActionPerformed(evt);
            }
        });
        menuReportes.add(subMenuDepartamentos);

        subMenuEstados.setText("Listado Estados");
        subMenuEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuEstadosActionPerformed(evt);
            }
        });
        menuReportes.add(subMenuEstados);

        subMenuTipoCuentas.setText("Listado Tipos Cuenta");
        subMenuTipoCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuTipoCuentasActionPerformed(evt);
            }
        });
        menuReportes.add(subMenuTipoCuentas);

        barraMenu.add(menuReportes);

        menuSalir.setText("Salir");

        subMenuSalir.setText("Salir");
        subMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuSalirActionPerformed(evt);
            }
        });
        menuSalir.add(subMenuSalir);

        barraMenu.add(menuSalir);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuSalirActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"¿Desea salir del sistema?", "Salir", JOptionPane.OK_CANCEL_OPTION) == 0){
            this.dispose();
            //new Login().setVisible(true);
            System.exit(0);
        }
    }//GEN-LAST:event_subMenuSalirActionPerformed

    private void subMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuClienteActionPerformed
        // TODO add your handling code here:
        FormCliente formCliente = new FormCliente();
        escritorio.add(formCliente);
        try {
            formCliente.setSelected(true);
            formCliente.moveToFront();
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_subMenuClienteActionPerformed

    private void subMenuCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMenuCuentaActionPerformed

    private void subMenuDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuDepartamentoActionPerformed
        // TODO add your handling code here:
        FormDepartamento formDepartamento = new FormDepartamento();
        escritorio.add(formDepartamento);
        try {
            formDepartamento.setSelected(true);
            formDepartamento.moveToFront();
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_subMenuDepartamentoActionPerformed

    private void subMenuEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuEstadoActionPerformed
        // TODO add your handling code here:
        FormEstado formEstado = new FormEstado();
        escritorio.add(formEstado);
        try {
            formEstado.setSelected(true);
            formEstado.moveToFront();
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_subMenuEstadoActionPerformed

    private void subMenuTipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuTipoCuentaActionPerformed
        // TODO add your handling code here:
        FormTipoCuenta formTipoCuenta = new FormTipoCuenta();
        escritorio.add(formTipoCuenta);
        try {
            formTipoCuenta.setSelected(true);
            formTipoCuenta.moveToFront();
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_subMenuTipoCuentaActionPerformed

    private void subMenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuClientesActionPerformed
        // TODO add your handling code here:
        FormListadoClientes formListadoClientes = new FormListadoClientes();
        escritorio.add(formListadoClientes);
        try {
            formListadoClientes.setSelected(true);
            formListadoClientes.moveToFront();
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_subMenuClientesActionPerformed

    private void subMenuDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuDepartamentosActionPerformed
        // TODO add your handling code here:
        FormListadoDepartamento formListadoDepartamento = new FormListadoDepartamento();
        escritorio.add(formListadoDepartamento);
        try {
            formListadoDepartamento.setSelected(true);
            formListadoDepartamento.moveToFront();
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_subMenuDepartamentosActionPerformed

    private void subMenuEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuEstadosActionPerformed
        // TODO add your handling code here:
        FormListadoEstados formListadoEstados = new FormListadoEstados();
        escritorio.add(formListadoEstados);
        try {
            formListadoEstados.setSelected(true);
            formListadoEstados.moveToFront();
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_subMenuEstadosActionPerformed

    private void subMenuTipoCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuTipoCuentasActionPerformed
        // TODO add your handling code here:
        FormListadoTipoCuentas formListadoTipoCuentas = new FormListadoTipoCuentas();
        escritorio.add(formListadoTipoCuentas);
        try {
            formListadoTipoCuentas.setSelected(true);
            formListadoTipoCuentas.moveToFront();
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_subMenuTipoCuentasActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menuMovimientos;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JCheckBoxMenuItem subMenuCliente;
    private javax.swing.JMenuItem subMenuClientes;
    private javax.swing.JCheckBoxMenuItem subMenuCuenta;
    private javax.swing.JCheckBoxMenuItem subMenuDepartamento;
    private javax.swing.JMenuItem subMenuDepartamentos;
    private javax.swing.JCheckBoxMenuItem subMenuEstado;
    private javax.swing.JMenuItem subMenuEstados;
    private javax.swing.JMenuItem subMenuMovimiento;
    private javax.swing.JMenuItem subMenuSalir;
    private javax.swing.JCheckBoxMenuItem subMenuTipoCuenta;
    private javax.swing.JMenuItem subMenuTipoCuentas;
    private javax.swing.JMenu subMenuUsuario;
    // End of variables declaration//GEN-END:variables
}
