
package vistas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author oscar
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        lblUsuario.setText("Usuario: " + Sesion.getUsuario().getNombre() + " " + Sesion.getUsuario().getApellido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        lblUsuario = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        subMenuUsuario = new javax.swing.JMenu();
        subMenuCliente = new javax.swing.JCheckBoxMenuItem();
        subMenuCuenta = new javax.swing.JCheckBoxMenuItem();
        subMenuDepartamento = new javax.swing.JCheckBoxMenuItem();
        subMenuEstado = new javax.swing.JCheckBoxMenuItem();
        subMenuSucursal = new javax.swing.JCheckBoxMenuItem();
        subMenuTipoCuenta = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        menuMovimientos = new javax.swing.JMenu();
        subMenuMovimiento = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        subMenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsuario.setText("jLabel1");

        escritorio.setLayer(lblUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(621, Short.MAX_VALUE)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(393, Short.MAX_VALUE))
        );

        subMenuUsuario.setText("Catalogos");

        subMenuCliente.setSelected(true);
        subMenuCliente.setText("Cliente");
        subMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuClienteActionPerformed(evt);
            }
        });
        subMenuUsuario.add(subMenuCliente);

        subMenuCuenta.setSelected(true);
        subMenuCuenta.setText("Cuenta");
        subMenuCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCuentaActionPerformed(evt);
            }
        });
        subMenuUsuario.add(subMenuCuenta);

        subMenuDepartamento.setSelected(true);
        subMenuDepartamento.setText("Departamento");
        subMenuDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuDepartamentoActionPerformed(evt);
            }
        });
        subMenuUsuario.add(subMenuDepartamento);

        subMenuEstado.setSelected(true);
        subMenuEstado.setText("Estado");
        subMenuEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuEstadoActionPerformed(evt);
            }
        });
        subMenuUsuario.add(subMenuEstado);

        subMenuSucursal.setSelected(true);
        subMenuSucursal.setText("Sucursal");
        subMenuUsuario.add(subMenuSucursal);

        subMenuTipoCuenta.setSelected(true);
        subMenuTipoCuenta.setText("Tipo Cuenta");
        subMenuUsuario.add(subMenuTipoCuenta);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Usuario");
        subMenuUsuario.add(jCheckBoxMenuItem1);

        barraMenu.add(subMenuUsuario);

        menuMovimientos.setText("Movimientos");

        subMenuMovimiento.setText("Movimiento");
        menuMovimientos.add(subMenuMovimiento);

        barraMenu.add(menuMovimientos);

        menuSalir.setText("Salir");

        subMenuSalir.setText("Salir");
        subMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuSalirActionPerformed(evt);
            }
        });
        menuSalir.add(subMenuSalir);

        barraMenu.add(menuSalir);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuSalirActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"¿Desea salir del sistema?", "Salir", JOptionPane.OK_CANCEL_OPTION) == 0){
            this.dispose();
            //new Login().setVisible(true);
            System.exit(0);
        }
    }//GEN-LAST:event_subMenuSalirActionPerformed

    private void subMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuClienteActionPerformed
        // TODO add your handling code here:
        FormCliente formCliente = new FormCliente();
        escritorio.add(formCliente);
        try {
            formCliente.setSelected(true);
            formCliente.moveToFront();
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_subMenuClienteActionPerformed

    private void subMenuCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMenuCuentaActionPerformed

    private void subMenuDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuDepartamentoActionPerformed
        // TODO add your handling code here:
        FormDepartamento formDepartamento = new FormDepartamento();
        escritorio.add(formDepartamento);
        try {
            formDepartamento.setSelected(true);
            formDepartamento.moveToFront();
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_subMenuDepartamentoActionPerformed

    private void subMenuEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuEstadoActionPerformed
        // TODO add your handling code here:
        FormEstado formEstado = new FormEstado();
        escritorio.add(formEstado);
        try {
            formEstado.setSelected(true);
            formEstado.moveToFront();
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_subMenuEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menuMovimientos;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JCheckBoxMenuItem subMenuCliente;
    private javax.swing.JCheckBoxMenuItem subMenuCuenta;
    private javax.swing.JCheckBoxMenuItem subMenuDepartamento;
    private javax.swing.JCheckBoxMenuItem subMenuEstado;
    private javax.swing.JMenuItem subMenuMovimiento;
    private javax.swing.JMenuItem subMenuSalir;
    private javax.swing.JCheckBoxMenuItem subMenuSucursal;
    private javax.swing.JCheckBoxMenuItem subMenuTipoCuenta;
    private javax.swing.JMenu subMenuUsuario;
    // End of variables declaration//GEN-END:variables
}
